name: Agent OS Code Review

on:
  # Weekly schedule - Sundays at 2 AM UTC
  schedule:
    - cron: '0 2 * * 0'
  
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      review_type:
        description: 'Type of review'
        required: true
        default: 'audit'
        type: choice
        options:
        - audit
        - security
        - review

jobs:
  code-review:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent runaway costs
    
    steps:
    # Harden runner for supply chain security
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde  # v2.9.1
      with:
        egress-policy: audit
    
    # Checkout - pinned by SHA for security
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      with:
        fetch-depth: 0
    
    # Setup Python with dependency caching
    - name: Setup Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Run Agent OS Code Review
      uses: securedotcom/agent-os-action@v2.1.0  # Our action - use semver tag
      with:
        review-type: ${{ github.event.inputs.review_type || 'audit' }}
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Upload artifacts - pinned by SHA
    - name: Upload Review Reports
      if: always()
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
      with:
        name: code-review-reports
        path: .agent-os/reviews/
        retention-days: 90

