name: Agent OS Code Review

on:
  # Weekly schedule - Sundays at 2 AM UTC
  schedule:
    - cron: '0 2 * * 0'
  
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      review_type:
        description: 'Type of review'
        required: true
        default: 'audit'
        type: choice
        options:
        - audit
        - security
        - review

jobs:
  code-review:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout - pinned by SHA for security
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      with:
        fetch-depth: 0
    
    - name: Run Agent OS Code Review
      uses: securedotcom/agent-os-action@v1  # Our action - use semver tag
      with:
        review-type: ${{ github.event.inputs.review_type || 'audit' }}
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Upload artifacts - pinned by SHA
    - name: Upload Review Reports
      if: always()
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
      with:
        name: code-review-reports
        path: .agent-os/reviews/
        retention-days: 90

