name: Multi-Agent Code Review

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  multi-agent-review:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Multi-agent mode takes longer
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde  # v2.9.1
        with:
          egress-policy: audit
      
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          fetch-depth: 0  # Full history for better analysis
      
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Run Multi-Agent Code Review
        id: review
        uses: securedotcom/agent-os-action@v2.1.0
        with:
          # Multi-Agent Configuration
          multi-agent-mode: 'sequential'  # Run 5 specialized agents
          
          # AI Provider
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Cost/Latency Guardrails
          max-files: 100
          max-tokens: 8000
          cost-limit: '5.0'  # Higher limit for multi-agent ($0.75 typical)
          
          # Fail Conditions
          fail-on: 'security:critical,security:high'
          
          # Reporting
          upload-reports: true
          comment-on-pr: false  # Not a PR workflow
      
      - name: Review Summary
        run: |
          echo "## 🤖 Multi-Agent Review Complete"
          echo ""
          echo "**Mode**: 5 Specialized Agents (Sequential)"
          echo "**Agents**: Security, Performance, Testing, Quality, Orchestrator"
          echo ""
          echo "### Results"
          echo "- **Blockers**: ${{ steps.review.outputs.blockers }}"
          echo "- **Suggestions**: ${{ steps.review.outputs.suggestions }}"
          echo "- **Files Analyzed**: ${{ steps.review.outputs.files-analyzed }}"
          echo "- **Cost**: \$${{ steps.review.outputs.cost-estimate }}"
          echo "- **Duration**: ${{ steps.review.outputs.duration-seconds }}s"
          echo ""
          echo "### Reports"
          echo "- Main Report: ${{ steps.review.outputs.report-path }}"
          echo "- SARIF: ${{ steps.review.outputs.sarif-path }}"
          echo "- JSON: ${{ steps.review.outputs.json-path }}"
          echo "- Individual Agent Reports: .agent-os/reviews/agents/"
      
      - name: Upload SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.review.outputs.sarif-path }}
          category: agent-os-multi-agent
        continue-on-error: true
      
      - name: Upload Review Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: multi-agent-review-reports
          path: .agent-os/reviews/
          retention-days: 90  # Keep for 3 months

# Multi-Agent Mode Benefits:
# ✅ 5 specialized agents (Security, Performance, Testing, Quality, Orchestrator)
# ✅ Deep, focused analysis per domain
# ✅ Orchestrator synthesizes and deduplicates findings
# ✅ Individual agent reports for detailed review
# ✅ Higher quality findings with better context
# 
# Cost Comparison:
# - Single-Agent: ~$0.15 per run
# - Multi-Agent Sequential: ~$0.75 per run (5x agents)
# 
# Time Comparison:
# - Single-Agent: 1-2 minutes
# - Multi-Agent Sequential: 5-10 minutes
# 
# When to Use Multi-Agent:
# ✅ Weekly/monthly deep audits
# ✅ Pre-release security reviews
# ✅ Compliance audits
# ✅ Large enterprise codebases
# ✅ High-stakes production code
# 
# When to Use Single-Agent:
# ✅ PR reviews (fast feedback)
# ✅ Daily CI checks
# ✅ Cost-conscious teams
# ✅ Small-medium codebases

