labels: [show-and-tell]
body:
  - type: markdown
    attributes:
      value: |
        ## 🎉 Show and Tell
        
        Share what you've built with Argus!
        
  - type: input
    id: project
    attributes:
      label: Project Name
      description: What's your project called?
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us about your project
      placeholder: |
        - What does it do?
        - How are you using Argus?
        - What results have you seen?
    validations:
      required: true
  
  - type: input
    id: link
    attributes:
      label: Link (optional)
      description: Link to your project, blog post, or demo
  
  - type: textarea
    id: metrics
    attributes:
      label: Results/Metrics
      description: Share any interesting findings or metrics
      placeholder: |
        - Vulnerabilities found: 15
        - False positives: 2 (87% reduction)
        - Time saved: 10 hours per week
